// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Server.Models;

public partial class StarCat_Context : DbContext
{
    public StarCat_Context() 
    {
    
    }
    public StarCat_Context(DbContextOptions<StarCat_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<TB_AUTHENTICATION> TB_AUTHENTICATION { get; set; }

    public virtual DbSet<TB_CHATHISTRY> TB_CHATHISTRY { get; set; }

    public virtual DbSet<TB_USER> TB_USERs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Thai_CI_AS");

        modelBuilder.Entity<TB_AUTHENTICATION>(entity =>
        {
            entity.HasKey(e => e.UserID);

            entity.ToTable("TB_AUTHENTICATION");

            entity.Property(e => e.UserID).HasMaxLength(50);
            entity.Property(e => e.CheckSum).HasMaxLength(50);
            entity.Property(e => e.EXT1).HasMaxLength(255);
            entity.Property(e => e.EXT1_FULLNAME).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Ext).HasMaxLength(100);
            entity.Property(e => e.JOBFUNCTION).HasMaxLength(100);
            entity.Property(e => e.MobilePhone).HasMaxLength(50);
            entity.Property(e => e.OrgId).HasMaxLength(40);
            entity.Property(e => e.Password).HasMaxLength(50);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.SupportGroupID).HasMaxLength(40);
        });

        modelBuilder.Entity<TB_CHATHISTRY>(entity =>
        {
            entity.HasKey(e => e.GUID);

            entity.ToTable("TB_CHATHISTRY");

            entity.Property(e => e.GUID).HasMaxLength(50);
            entity.Property(e => e.COLOR).HasMaxLength(7);
            entity.Property(e => e.FILENAME).HasMaxLength(50);
            entity.Property(e => e.FULLNAMESENDER).HasMaxLength(50);
            entity.Property(e => e.IDRECIVER).HasMaxLength(50);
            entity.Property(e => e.IDSENDER).HasMaxLength(50);
            entity.Property(e => e.MESSAGE).HasMaxLength(50);
            entity.Property(e => e.NAMEDRECIVER).HasMaxLength(50);
        });

        modelBuilder.Entity<TB_USER>(entity =>
        {
            entity.HasKey(e => e.USER_ID);

            entity.ToTable("TB_USER");

            entity.Property(e => e.USER_ID)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.ADDRESS).HasMaxLength(255);
            entity.Property(e => e.ActiveDirectory).HasDefaultValue(false);
            entity.Property(e => e.CITIZENID).HasMaxLength(20);
            entity.Property(e => e.DATECREATED)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DATEMODIFILED).HasColumnType("datetime");
            entity.Property(e => e.DRIVINGLICENSE).HasMaxLength(20);
            entity.Property(e => e.EMAIL).HasMaxLength(50);
            entity.Property(e => e.EXT1).HasMaxLength(255);
            entity.Property(e => e.EXT2).HasMaxLength(255);
            entity.Property(e => e.FIRSTNAME).HasMaxLength(50);
            entity.Property(e => e.IMAGE).HasColumnType("image");
            entity.Property(e => e.JOBFUNCTION).HasMaxLength(1000);
            entity.Property(e => e.LASTNAME).HasMaxLength(50);
            entity.Property(e => e.LineID).HasMaxLength(100);
            entity.Property(e => e.ManagerLavel).HasMaxLength(100);
            entity.Property(e => e.ManagerLevel).HasMaxLength(100);
            entity.Property(e => e.ManagerUserID).HasMaxLength(100);
            entity.Property(e => e.ManagerUserID2).HasMaxLength(100);
            entity.Property(e => e.ManagerUserID3).HasMaxLength(100);
            entity.Property(e => e.ORGID).HasMaxLength(40);
            entity.Property(e => e.PHONEHOME).HasMaxLength(255);
            entity.Property(e => e.PHONEMOBILE).HasMaxLength(255);
            entity.Property(e => e.PHONEWORK).HasMaxLength(255);
            entity.Property(e => e.SecondaryDeputy).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}