// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class TB_AUTHENTICATION
{
    public string UserID { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string SupportGroupID { get; set; }

    public int? Permission { get; set; }

    public string CheckSum { get; set; }

    public string Description { get; set; }

    public string Email { get; set; }

    public string Ext { get; set; }

    public int? Role { get; set; }

    public string OrgId { get; set; }

    public string Phone { get; set; }

    public string MobilePhone { get; set; }

    public bool? RoleAdmin { get; set; }

    public bool? RoleHelpdesk { get; set; }

    public bool? RoleAsset { get; set; }

    public string OrgName { get; set; }

    public string DEP_Name { get; set; }

    public string LOCATION_Name { get; set; }

    public string SectionName { get; set; }

    public string SubSectionName { get; set; }

    public string DivisionName { get; set; }

    public bool? UserConnected { get; set; }

    public bool? StatusOfClient { get; set; }

    public bool? IsChat { get; set; }

    public string JOBFUNCTION { get; set; }

    public long? LastLogon { get; set; }

    public long? PasswordExpire { get; set; }

    public long? LastChangePassword { get; set; }

    public long? LastForgetPassword { get; set; }

    public bool? ChangePasswordAfterFirstLogon { get; set; }

    public int? DEP_ID { get; set; }

    public int? LOCATION_ID { get; set; }

    public string EXT1 { get; set; }

    public string EXT1_FULLNAME { get; set; }

    public bool? IsApproveUser { get; set; }

    public bool? IsBlocked { get; set; }

    public int? ChangePasswordCount { get; set; }

    public int? WrongPasswordCount { get; set; }

    public bool? manageScript { get; set; }

    public bool? ISDELETED { get; set; }

    public int? SECTION_ID { get; set; }

    public int? SUBSECTION_ID { get; set; }

    public int? DIV_ID { get; set; }

    public long? FK_BUILDING { get; set; }

    public long? FK_FLOOR { get; set; }

    public long? FK_ROOM { get; set; }
}