// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class TB_CHATHISTRY
{
    public string GUID { get; set; }

    public string IDSENDER { get; set; }

    public string FULLNAMESENDER { get; set; }

    public string IDRECIVER { get; set; }

    public string NAMEDRECIVER { get; set; }

    public string MESSAGE { get; set; }

    public string FILENAME { get; set; }

    public string COLOR { get; set; }
}